all: inicjacjaPlanszyZPliku.* losowaInicjacjaPlanszy.* plansza_t.h inicjacjaZpliku_test.c main.c
	gcc main.c inicjacjaPlanszyZPliku.c losowaInicjacjaPlanszy.c inicjacjaZpliku_test.c -o generujPlansze
